<?php

namespace AppBundle\Repository;

/**
 * CompaniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompaniaRepository extends \Doctrine\ORM\EntityRepository
{
}
