<?php

namespace AppBundle\Repository;

/**
 * EnsayoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnsayoRepository extends \Doctrine\ORM\EntityRepository
{
}
