<?php

namespace AppBundle\Repository;

/**
 * EquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoRepository extends \Doctrine\ORM\EntityRepository
{

	/**
	 * Busca los equipos pertenecientes a una persona por Id
	 *
	 * @param $personaId
	 *
	 * @return \Doctrine\ORM\QueryBuilder
	 */
	public function findEquiposByPersona($persona){

		$query = $this->createQueryBuilder('e')
		->innerJoin('e.personas','p')
		->where('p.id = :persona');

		$query->setParameter('persona',$persona);

		return $query;

	}
}
