<?php

namespace AppBundle\Repository;

/**
 * EstadisticaTemporalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadisticaTemporalRepository extends \Doctrine\ORM\EntityRepository
{
}
