<?php

namespace AppBundle\Repository;

/**
 * IntervencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervencionRepository extends \Doctrine\ORM\EntityRepository
{

    public function getQb()
    {
        return $this->createQueryBuilder('interv');
    }

    public function getUltimasIntervencionesByPozo($pozo)
    {
        $qb = $this->getQb()
            ->innerJoin('interv.pozo','pozo')
            ->where('pozo = :pozo')
            ->orderBy('interv.fecha','DESC')
            ->orderBy('interv.fechaCreacion','DESC');

        $qb->setParameter('pozo',$pozo);

        return $qb;
    }

    public function getUltimasIntervencionesByEquipo($equipo)
    {
        $qb = $this->getQb()
            ->innerJoin('interv.equipo','equipo')
            ->where('equipo = :equipo')
            ->orderBy('interv.fecha','DESC')
            ->orderBy('interv.fechaCreacion','DESC');

        $qb->setParameter('equipo',$equipo);

        return $qb;
    }

    public function getUltimaIntervencionByEquipo($equipo)
    {

        $intervencionesQb = $this->getUltimasIntervencionesByEquipo($equipo);

        $intervencionesQb->setMaxResults(1);

        return $intervencionesQb;
    }

    public function getIntervencionesByEquipos($equipos){

        $qb = $this->getQb()
            ->innerJoin('interv.equipo','equipo')
            ->where('equipo IN (:equipos)')
            ->orderBy('interv.fecha','DESC')
            ->orderBy('interv.fechaCreacion','DESC');

        $qb->setParameter('equipos',$equipos);

        return $qb;
    }

    public function getIntervencionesCerradasByEquipo($equipos){

        $qb = $this->getIntervencionesByEquipos($equipos);

        $qb->andWhere('interv.accion = 1');

        return $qb;
    }

    public function getIntervencionByEquipoyFecha($equipo,$fecha){

    	$qb = $this->getIntervencionesByEquipos($equipo);

    	$qb->andWhere('interv.fecha = :fecha');

    	$qb->setParameter('fecha',$fecha);

    	return $qb;
    }

    public function getUltimaIntervencionAperturaByEquipoyFecha($equipo,$fecha){

    	$qb = $this->getIntervencionByEquipoyFecha($equipo,$fecha);

    	$qb->andWhere('interv.accion = 0');

    	$qb->setMaxResults(1);

    	return $qb;
    }

}
