<?php

namespace AppBundle\Repository;

/**
 * ManiobraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManiobraRepository extends \Doctrine\ORM\EntityRepository
{
}
