<?php

namespace AppBundle\Repository;

/**
 * MensajeEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensajeEstadoRepository extends \Doctrine\ORM\EntityRepository
{
}
