<?php

namespace AppBundle\Repository;


use AppBundle\Entity\Persona;

/**
 * NotificacionEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificacionEstadoRepository extends \Doctrine\ORM\EntityRepository
{


    public function getQb()
    {
        return $this->createQueryBuilder('ne');
    }

    public function getIdsNotificacionesLeidasByPersona(Persona $persona)
    {

        $qb = $this->getQb();

        $qb ->select('n.id')
	        ->innerJoin('ne.notificacion','n')
            ->where('ne.leido = true')
            ->andWhere('ne.persona = :persona');

        $qb->setParameter('persona', $persona);

        return $qb;
    }
}
