<?php

namespace AppBundle\Repository;

/**
 * NotificacionDistribucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificacionDistribucionRepository extends \Doctrine\ORM\EntityRepository
{
}
