<?php

namespace AppBundle\Repository;

/**
 * PozoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PozoRepository extends \Doctrine\ORM\EntityRepository
{
}
