<?php

namespace AppBundle\Repository;

/**
 * RecursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecursoRepository extends \Doctrine\ORM\EntityRepository
{

	public function getQb()
	{
		return $this->createQueryBuilder('rec');
	}

	public function getRecursosByTipo($tipo = null){

		$qb = $this->getQb()
			->where('rec.tipoRecurso = :tipo')
			->andWhere('rec.activo = true');

		$qb->setParameter('tipo',$tipo);

		return $qb;

	}

	public function getReportes(){

		$trRepositoy = $this->getEntityManager()->getRepository('AppBundle:TipoRecurso');

		$tipoReporte = $trRepositoy->getBySlug('reporte')->getQuery()->getOneOrNullResult();

		return $this->getRecursosByTipo($tipoReporte);

	}

	public function getExtensiones(){

		$qb = $this->getQb()->select('rec.extension')->distinct(true);

		return $qb;
	}

	public function getRecursos(){

		$qb = $this->getQb()->select('rec.recurso')->distinct(true);

		return $qb;

	}
}
