<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Equipo;

/**
 * TransporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransporteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTransportesByEquipo(Equipo $equipo)
    {
        return $this->createQueryBuilder('tr')->where('tr.equipo = :equipo')->orderBy('tr.inicio', 'DESC')->setParameter('equipo', $equipo);
    }
}
