<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Equipo;
use Doctrine\ORM\EntityRepository;

/**
 * TransporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransporteRepository extends EntityRepository
{
    public function getTransportesByEquipo(Equipo $equipo, $orderBy = ['inicio' => 'DESC'], $inicio=null, $fin=null)
    {
        $query = $this->createQueryBuilder('tr')
          ->where('tr.equipo = :equipo')
          ->setParameter('equipo', $equipo);

        foreach ($orderBy as $key => $value) {
            $query->addOrderBy("tr.$key", $value);
        }

        if ($inicio) {
            $query->andWhere('tr.inicio >= :inicio')->setParameter('inicio', $inicio);
        }

        if ($fin) {
            $query->andWhere('tr.fin <= :fin')->setParameter('fin', $fin);
        }

        return $query;
    }
}
