<?php

namespace AppBundle\Repository;

/**
 * TuberiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TuberiaRepository extends \Doctrine\ORM\EntityRepository
{
}
