<?php

namespace UsuarioBundle\Repository;

/**
 * AccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccionRepository extends \Doctrine\ORM\EntityRepository
{
}
