<?php

namespace UsuarioBundle\Repository;

use UsuarioBundle\Entity\Accion;
use UsuarioBundle\Entity\Funcionalidad;

/**
 * FuncionalidadAccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuncionalidadAccionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQb()
    {
        return $this->createQueryBuilder('fa');
    }

    public function getByFuncionalidadYAccion(Funcionalidad $funcionalidad, Accion $accion)
    {
        return $this->getQb()
          ->where('fa.funcionalidad = :funcionalidad')
          ->andWhere('fa.accion = :accion')
          ->setParameter('funcionalidad', $funcionalidad)
          ->setParameter('accion', $accion);
    }
}
