<?php

namespace UsuarioBundle\Repository;

/**
 * FuncionalidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuncionalidadRepository extends \Doctrine\ORM\EntityRepository
{
}
