<?php

namespace UsuarioBundle\Repository;

/**
 * FuncionalidadRolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuncionalidadRolRepository extends \Doctrine\ORM\EntityRepository
{
}
