<?php

namespace UsuarioBundle\Repository;

/**
 * FuncionalidadAccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuncionalidadAccionRepository extends \Doctrine\ORM\EntityRepository
{
}
