<?php

namespace UsuarioBundle\Repository;

/**
 * LogAccesoDenegadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogAccesoDenegadoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQb()
    {
        return $this->createQueryBuilder('log');
    }

    public function getOrderByFecha($sort = "DESC")
    {
        return $this->getQb()->orderBy('log.fecha', $sort);
    }
}
