<?php

namespace UsuarioBundle\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{

    public function getQb()
    {
        return $this->createQueryBuilder('menu');
    }

    public function getRootsActivos()
    {
        $qb = $this->getQb()
            ->leftJoin('menu.accion','acc')
            ->where('menu.activo = true')
            ->andWhere('menu.padre IS NULL')
            ->orderBy('menu.orden','ASC');

        return $qb;
    }
}
