<?php

namespace UsuarioBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByUniqueEmail(array $criteria)
	{
		return $this->findBy($criteria);
	}

	public function findByUniqueUsername(array $criteria)
	{
		return $this->findBy($criteria);
	}
}
